### ISSUE TITLE
Support for ZBMINI-L2

### ISSUE THREAD

**Issue by stefan-schweiger** [StyraHem/Homey.Sonoff.Zigbee#1]
I'm opening this issue to express my interest in getting support for the ZBMINI-L2. But also to find out if there is any interest in community contributions and PRs. I'm willing to implement this, but I would like to know if it even has the potential of getting merged before starting the work.

**Comment by hakana** [comment]
Yes we will add support for that and if you do a PR it help.
________________________________
From: Stefan Schweiger ***@***.***>
Sent: Thursday, January 25, 2024 11:52:59 PM
To: StyraHem/Homey.Sonoff.Zigbee ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StyraHem/Homey.Sonoff.Zigbee] Support for ZBMINI-L2 (Issue #1)


I'm opening this issue to express my interest in getting support for the ZBMINI-L2. But also to find out if there is any interest in community contributions and PRs. I'm willing to implement the support for this, but I would like to know if it even has the potential of getting merged before starting the work.

**Comment by stefan-schweiger** [comment]
@hakana I've created a PR which adds support. Only thing I couldn't really figure out is how to change the switch type / switch action. So if there is some input from your side it would be appreciated. Let me know what you think besides that.
